# File: wrangler.toml
# Cấu hình
name = "call-redirect"
main = "src/index.js"
compatibility_date = "2025-09-04"

routes = [
  "call.rungkhoai.com/*"
]


kv_namespaces = [
  { binding = "SALES_PHONES", id = "${SALES_PHONES_NAMESPACE_ID}" }
]
